### ISSUE TITLE
two clients assigned the same internal client ID

### ISSUE THREAD

**Issue by Kevin0626** [eclipse/wakaama#403] opened 2018-11-28 09:33 UTC
Here is the situation:
Two client devices both are in registered status and notifying data to the wakaama server. However only one client can be seen from the server side.

The possible reason:
one client (#1) is actually a process running in the same machine as wakaama server, another client (#2) is an independent device. The server and client #1 both had a  reboot and client #1 registered as ID 0. however the client#2 was also registered as internal ID 0 previously.  Now the server and both clients can not tell any problem for this situation.

Solution options:
1. the wakaama server should not always start allocating internal ID from 0. It better be some random number. That can reduce the possibility of this situation
2. the wakaama server can check the source IP/port for Update/Notify messages and reject it if not match the original address from registration. The current wakaama design is just update the client to the new source address.

@dnav could you please give some comments on this issue?

**Comment by dnav** [comment] 2018-12-07 14:07
I guess you are not using any DTLS which would prevent this issue.

option 2. is not feasable since this is the expected behavior. A registered Client may have a new external IP address due to NAT.

**Comment by sbernard31** [comment] 2020-11-03 17:29
@Kevin0626  should we close this issue ?

**Comment by sbernard31** [comment] 2020-11-30 09:34
I close this issue but feel free to reopen if needed.

**Closed by sbernard31** 2020-11-30 09:34 UTC
Labels: question
