### ISSUE TITLE
registration time out when prv_updateRegistration msg lost

### ISSUE THREAD

**Issue by zhenglining** [eclipse/wakaama#479] opened 2020-08-28 08:01 UTC
when update hearbeat with prv_updateRegistration , client will enter STATE_REG_UPDATE_PENDING status, normally server will response and client enter STATE_REGISTERED status, everythins is ok. 
However, when the msg of prv_updateRegistration sent by transaction_send lost, server cannot response a update register msg(this probability is quite high in wireless connection), client still in STATE_REG_UPDATE_PENDING status all the time, so registration will time out in the end.
maybe when client enter STATE_REG_UPDATE_PENDING  status for a while, it should update registration again to keep the connection.

**Comment by sbertin-telular** [comment] 2020-08-28 13:37
The registration update is a confirmable message, so multiple attempts are made to update the registration. When the transaction finishes all attempts and times out, the client will set the server to STATE_REG_FAILED. I believe it is 5 attempts over 247s with increasing delays between attempts before timeout.

It could be argued that a registration update timeout before the registration lifetime has expired should return to STATE_REGISTERED status and try again later. At that point though it has already proven an inability to communicate with the server and a new registration with a new connection may be the safer option.

**Comment by UnforgivenD** [comment] 2020-09-10 13:40
hi, 
it seems that we have similar issue with wakaama (we running performance test of 3000 wakaama clients connected to one leshan server, 37 of them failed out after ~15 mins, and seems that it happens because of failing to update registration), client/server  log attached.
will appreciate any help.

[28873e8d_0625_106_client.log](https://github.com/eclipse/wakaama/files/5202007/28873e8d_0625_106_client.log)
[by_port_example1.log](https://github.com/eclipse/wakaama/files/5202009/by_port_example1.log)

**Comment by sbernard31** [comment] 2020-09-10 15:33
Generally Leshan Server initiate an handshake when it does not have dtls connection for a device.
This generally happens when you persist registration and you restart the server.
If you don't do that I suspect that the server initiated handshake failures hide another issue.

> @sbernard31 do you know, how to setup the wakaama client to accept a CLIENT_HELLO, if the client has still a established session?

I made it works long time ago but I'm not up to date now. 
See  https://github.com/eclipse/wakaama/issues/398. It worked after some little fix which was merged in master.

**Comment by UnforgivenD** [comment] 2020-09-11 10:25
Thanks for answers.
Unfortunately it seems that leshan setting doesn't help, all clients was kicked off exactly after 4 updates (client log attached). 
Maybe there is other options?
[client_kicked_out_4_updates.txt](https://github.com/eclipse/wakaama/files/5208316/client_kicked_out_4_updates.txt)

**Comment by UnforgivenD** [comment] 2020-09-11 11:15
and seems that happens because of this 
020-09-11 07:31:07.608 DEBUG 13896 --- [DTLS-Connection-Handler-16] o.e.californium.scandium.DTLSConnector   : Sending application layer message to [IP(172.19.1.13:56745)]
2020-09-11 07:31:07.608  WARN 13896 --- [DTLS-Connection-Handler-16] s.a.l.c.MessageSenderErrorCallback       : onError of message send callback

org.eclipse.leshan.core.request.exception.SendFailedException: Unable to send request coap://172.19.1.13:56745/3/0/15
        at org.eclipse.leshan.core.californium.CoapAsyncRequestObserver.onSendError(CoapAsyncRequestObserver.java:102) [leshan-core-cf-1.0.0-ODED.jar!/:na]
        at org.eclipse.californium.core.coap.Message.setSendError(Message.java:885) [californium-core-2.0.0-M18.jar!/:na]
        at org.eclipse.californium.core.coap.Request.setSendError(Request.java:815) [californium-core-2.0.0-M18.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:990) [californium-core-2.0.0-M18.jar!/:na]
        at org.eclipse.californium.elements.RawData.onError(RawData.java:303) [element-connector-2.0.0-M18.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector.sendMessage(DTLSConnector.java:1962) [scandium-2.0.0-M18.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector.access$1500(DTLSConnector.java:215) [scandium-2.0.0-M18.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector$13.run(DTLSConnector.java:1870) [scandium-2.0.0-M18.jar!/:na]
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) [element-connector-2.0.0-M18.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
Caused by: org.eclipse.californium.elements.exception.EndpointUnconnectedException: server only, resumption required!

**Comment by sbernard31** [comment] 2020-09-11 12:36
The error is because you try to send a request to a device for which you have no DTLS connection.
(before Leshan tried to initiate an handshake, now you set Leshan as server only so it says there is no DTLS connection for this device and so he can not send the request.

The question is why you lost the DTLS connection ?
E.G. this could be because device close it (by sending close_notify) 
I tried to look at your device log but I don't get it. Maybe a wireshark capture could help you to find what happens.

**Comment by sbernard31** [comment] 2020-11-03 16:13
@UnforgivenD  can we close this issue ?

**Comment by UnforgivenD** [comment] 2020-11-03 16:15
yes, thanks for help, closing it.

**Closed** 2020-11-03 16:18 UTC
