### ISSUE TITLE
`registration_getStatus` issue

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#406] opened 2018-11-29 13:06 UTC
In `registration_getStatus` function, if `status` is `STATE_DEREG_PENDING`, the following registration status is returned: `STATE_REG_FAILED`

**Comment by sbernard31** [comment] 2020-11-03 17:24
@sbertin-telular is it sill valid for v1.0 or master branch ?

**Comment by sbertin-telular** [comment] 2020-11-04 19:32
Yes, it is still valid.

**Comment by qleisan** [comment] 2021-02-09 16:30
[client_states.pptx](https://github.com/eclipse/wakaama/files/5952441/client_states.pptx)

It is not clear (to me) what the problem is that should be fixed. `registration_getStatus()` "aggregates" a number of `lwm2m_status_t` states according to this logic (quoted from the function definition)

> Returns STATE_REG_PENDING if at least one registration is still pending
> Returns STATE_REGISTERED if no registration is pending and there is at least one server the client is registered to
> Returns STATE_REG_FAILED if all registration failed. 
 
The `lwm2m_step()` handles the `lwm2m_client_state_t` state transition logic using `registration_getStatus()`. A STATE_REG_FAILED response result in a state transition to STATE_BOOTSTRAP_REQUIRED, see attached powerpoint.
Aggregating and "reusing" a state name like this can be confusing but the logic is correct or am I missing something?

**Comment by sbernard31** [comment] 2021-02-09 16:56
I'm not sure to understand too, but maybe the question is : 
If we have a server in STATE_**DEREG_PENDING**,  do we consider we still are in a REGISTERED state or are we already considering we are in a FAILED state ?

> Aggregating and "reusing" a state name like this can be confusing but the logic is correct or am I missing something?

I agree.

**Comment by tuve** [comment] 2021-02-10 13:54
Yes I think we should have a separate response codes for the aggregated states. It is currently only used in by one other function but I also think we should consider renaming the function since that in combination of the reused return type is a bit confusing. I also think *_PENDING, *_REGISTERED, *_UNREGISTERED, not saying anything about the cause as to why it is unregistered.

**Comment by qleisan** [comment] 2021-02-10 15:21
PR #538 updates `registration_getStatus()` so that a server connection in state `STATE_DEREG_PENDING` is considered as still registered. This makes sense and is safe. If no reply is received from any retransmission, transaction timeout will cause transition to `STATE_DEREGISTERED` anyway. Little practical difference for the client state logic (only timing).

Not including refactoring in this bugfix. New states to solve the "reuse" problem is not without drawbacks, suggest a separate improvement issue if we want to refactor this, also including the `bootstrap_getStatus()` function.

**Closed** 2021-02-12 13:27 UTC
Labels: bug
