### ISSUE TITLE
messed handling in observing 1/0 and 1/0/0

### ISSUE THREAD

**Issue by Kevin0626** [eclipse/wakaama#381] opened 2018-07-13 07:38 UTC

**Comment by Kevin0626** [comment] 2018-07-13 07:54
a bit more test:
if the second observe call if after the completion of the first call. then the result is no problem.

18-07-13 15:37:21 [W:LWM2M] Observe [lwm2mdaemon-m:/1/0] started. current status: 0. cid=0
18-07-13 15:37:21 [I:LWM2M] ->OBS: Observed [lwm2mdaemon-m],uri=/1/0/ number=0, fmt=11543, datalen=144, ctxid=0
    144 bytes received of type application/vnd.oma.lwm2m+json:
    {"bn":"/1/0/","e":[{"n":"0","v":123},{"n":"1","v":300},{"n":"2","v":0},{"n":"3","v":0},{"n":"5","v":0},{"n":"6","bv":false},{"n":"7","sv":"U"}]}
18-07-13 15:37:21 [W:LWM2M] obs_notify_callback: obs successed, client=lwm2mdaemon-m, uri=/1/0/

18-07-13 15:38:21 [W:LWM2M] Observe [lwm2mdaemon-m:/1/0/0] started. current status: 0. cid=1
18-07-13 15:38:21 [I:LWM2M] ->OBS: Observed [lwm2mdaemon-m],uri=/1/0/ number=0, fmt=11543, datalen=40, ctxid=1
    40 bytes received of type application/vnd.oma.lwm2m+json:
    {"bn":"/1/0/0/","e":[{"n":"0","v":123}]}

**Comment by Kevin0626** [comment] 2018-07-13 08:03
still some error in the above log:
in the second observe call, the uri passed in is /1/0/0, however the callback return the uri is /1/0. 

but from the payload of second callback. the bn is "/1/0/0/".

**Comment by boria8** [comment] 2018-07-13 20:21
Hi Kevin,
I think that the root cause of the last issue you have reported is #378 issue.

**Comment by Kevin0626** [comment] 2018-07-14 12:33
@boria8 thanks!

I didn't get full understanding about #378. do you have any patch? I may test if it can fix our issues.

**Comment by sbernard31** [comment] 2020-11-03 17:36
Duplicate of #378

**Closed by sbernard31** 2020-11-03 17:36 UTC
